[package]
name = "wschatrs"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[dependencies]
tungstenite = "0.10.1"
env_logger = "0.6.1"
url = "2.1.1"

[[bin]]
    name = "server"
    path = "src/server.rs"

[[bin]]
    name = "client"
    path = "src/client.rs"